name: Build and Push Multi-Platform Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # 匹配任何以 v 开头的标签
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 允许创建 Release 和上传文件
      packages: write    # 允许推送 Docker 镜像
      actions: write     # 允许使用缓存
      id-token: write    # 可能需要用于 OIDC 身份验证
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
        install: true
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/plex-zh
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=tag
          type=raw,value=latest
      
    - name: Build and push multi-platform image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Multi-platform Docker image built for:
          - AMD64
          - ARM64
          - ARMv7
          
          ### Docker Pull Commands
          ```bash
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/plex-zh:${{ github.ref_name }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/plex-zh:latest
          ```
        # 移除了 files 参数，因为我们不需要上传文件
        # 添加 token 参数使用 releas token
        token: ${{ secrets.RELEASE_TOKEN }}  # 使用自定义令牌
